export enum ActionType {
  TASK_START = 'TASK_START',
  TASK_END = 'TASK_END',
  CASE_START = 'CASE_START',
  CASE_SUBMIT = 'CASE_SUBMIT',
  CASE_ERROR = 'CASE_ERROR',
  ORDER_SELECT = 'ORDER_SELECT'
}

export enum TaskType {
  ORDER_ASSIGNMENT = 'ORDER_ASSIGNMENT',
  ORDER_VALIDATION = 'ORDER_VALIDATION',
  DELIVERY_SCHEDULING = 'DELIVERY_SCHEDULING'
} 